import type { Metadata } from 'next';
import Image from 'next/image';
import { Geist, Geist_Mono } from 'next/font/google';
import { Footer, Layout, Navbar } from 'nextra-theme-docs';
import { Head } from 'nextra/components';
import { getPageMap } from 'nextra/page-map';

import '@/app/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'DirectFN Pro12 – User Guide',
    template: '%s | DirectFN Pro12',
  },
  description: 'Generated by create next app',
};

const navbar = (
  <Navbar
    logo={
      <Image
        src='/logo.png'
        alt='logo'
        width={100}
        height={100}
      />
    }
  />
);
// const footer = <Footer>{process.env.version} © DirectFN. </Footer>;
const footer = (
  <Footer className='items-center flex-row justify-between'>
    <p>{new Date().getFullYear()} © DirectFN.</p>
    <p>v{process.env.APP_VERSION}</p>
  </Footer>
);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <Head />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Layout
          navbar={navbar}
          pageMap={await getPageMap()}
          sidebar={{ autoCollapse: true, defaultMenuCollapseLevel: 1 }}
          footer={footer}
          navigation={{
            prev: true,
            next: true,
          }}
          editLink={null}
          feedback={{ content: null, labels: '' }}
        >
          {children}
        </Layout>
      </body>
    </html>
  );
}
