const meta = {
  'depth-by-price': '',
  'depth-by-order': '',
  'time-and-sales': '',
  'time-and-sales-summary': '',
  'detail-quote': '',
  'full-quote': '',
  'cash-flow-detail-quote': '',
  'trading-monitor': '',
  'price-alert': '',
  ratios: '',
  financial: '',
  'company-information': '',
  'company-management': '',
  'company-owners': '',
  'company-subsidiaries': '',
  'technical-score': '',
  'fundamental-score': '',
  'historical-performance': '',
  'dividend-and-actions': '',
  'fair-value': '',
  'history-data': '',
  announcements: '',
  news: '',
  graph: '',
  'volume-progress': '',
  'vwap-chart': '',
  'cash-flow-chart': '',
  'option-chain': '',
};

export default meta;
